### ISSUE TITLE
Error running inline Azure

### ISSUE THREAD

**Issue by richardhauer** [XpiritBV/Vsts-Build-Task-InlinePowershell#12]
I am getting the error as follows:

`Exception calling "GetTempFileName" with "0" argument(s): "The file exists.`

This blocks the execution of the task.  I will dig through the code to see if I can fix it, but in the meantime please advise if this is a known issue.

**Comment by richardhauer** [comment]
Never mind - turns out there was 65k files in `C:\Windows\Temp` and that the error is an O/S level issue.

**Comment by baruchiro** [comment]
Consider to clear the `C:\Users\{User}\AppData\Local\Temp` directory.

Or just use the new official beta extension: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=tfs-2018

**Comment by baruchiro** [comment]
@XpiritBV I think you need to reopen this and fix it. We can't let our builds fail.
