### ISSUE TITLE
The term 'Import-VstsLocStrings' is not recognized as the name of a cmdlet, when running Azure Inline powershell with TFS 2015.2.1 Release Management Agent

### ISSUE THREAD

**Issue by chamindac** [XpiritBV/Vsts-Build-Task-InlinePowershell#3]
I am ruining inline azure powershell task in  TFS2015.2.1 TFS build/release agent. This is running all azure PS scripts fine when checked in as files and executed via default Azure PowerShell task. same script running with inline task fails. Even simple hello world fails with below error.

```
2016-06-30T05:11:19.1776768Z ##[error]The term 'Import-VstsLocStrings' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

2016-06-30T05:11:19.5214293Z ##[error]The term 'Trace-VstsEnteringInvocation' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

2016-06-30T05:11:20.0995471Z ##[error]The term 'Trace-VstsLeavingInvocation' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

2016-06-30T05:11:20.0995471Z ##[error]The term 'Get-VstsInput' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

2016-06-30T05:11:20.1932974Z ##[command]& 'C:\Users\rmagent\AppData\Local\Temp\tmp5A0B.ps1'
```

![image](https://cloud.githubusercontent.com/assets/20109548/16477266/f043c2f8-3ead-11e6-9396-1d2ea6d2cc73.png)

I investigated and found you are using VstsTaskSdk. Tried to add it to my agents machine powershell modules folder and  import module from within the agent machine works fine and i can execute failing commands. Still it fails with the task in release management. Is there any specif activity required to use the extension with on-premise TFS 2015.2.1?

**Comment by pgroene** [comment]
It seems there is an error in Select-AzureSubscription.
I haven't tested on TFS 2015.2.1, but I can try to add the module to task. Some other thinks what can be wrong:
- version of azure powershell, update it to the lastes version
- can you try an other authentication scheme?

I do not have a TFS 2015.2.1, so when I have a fix, whould you be able to test it for me. If so can you share your VSTS account so I can share a private fix?

**Comment by jessehouwing** [comment]
Private versions can't be downloaded to install to TFS. You'll need to
attach the vsix to the GitHub issue.

**Comment by chamindac** [comment]
Sure I can test it .. If you share me the vsix. I am sure the Azure SDK and other things are ok in the tested agent. I can run same script on agent manually or using default azure powershell task to run a script file. Even a simple hello world print fails with inline. 

When I run script with continue as error action  , my script run fully connecting to azure subscription successfully. But fails the task since above errors.

**Comment by GlenAppleton** [comment]
I'm having this very same issue with on-prem TFS 2015 Update 2.  As @chamindac said in his post, running any PS script on the build server works fine, but this extension is throwing the import error.  I look forward to the next release that addresses this issue since many of our scripts are very simple on-line PS commands that could be replaced with this extension.

**Comment by pgroene** [comment]
I have created a fix for the issue, would you be able to test it?

[petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Build-InlinePowershell-1.1.2.vsix.zip](https://github.com/XpiritBV/Vsts-Build-Task-InlinePowershell/files/353818/petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Build-InlinePowershell-1.1.2.vsix.zip)

**Comment by GlenAppleton** [comment]
I just tried the update (I think), but it's hard to tell if it's the update or if the previous version didn't uninstall.  It's not showing up in the list of installed extensions but it is available in the deployment task list.  In any case, it's still throwing the same error.

**Comment by chamindac** [comment]
@pgroene  I removed 1.1.1 and installed 1.1.2 you shared. Still same issue is there as confirmed by @GlenAppleton . Tried with Azure classic and Azure RM subscriptions. Even hello world throws the exceptions I have posted above.

**Comment by pgroene** [comment]
I'm going do some more research. I'm not sure what line fails. When running a new agents it seems to work fine. In the case of the online agent connected to tfs server I do not get any errors.

**Comment by fredrik--johansson** [comment]
Any progress?

I ran into the same (or similiar) issue after the latest update of VSTS (Jul 29).

I can no longer use varaibles in the arguments lists when running the inline PS extension.
E.g.
```
2016-08-08T07:54:39.8776571Z ##[command]& 'C:\Users\buildguest\AppData\Local\Temp\tmp2985.ps1' -Version $(GitVersion_SemVer)
2016-08-08T07:54:56.8143535Z ##[error]The term 'GitVersion_SemVer' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

I get this error in both the hosted and on-prem agents.

**Comment by ddjong1971** [comment]
Hi Peter
I have the same problem on my (on premise) build agent.
Have you made any progress on the issue?

**Comment by loshurik** [comment]
I have TFS Version 14.102.25423.0, Task version is 1.1.6 (got from marketplace).
The issue lookes very similar
##[error]The term **'Import-VstsLocStrings' is not recognized** as the name of a cmdlet, function, script file, or operable program.** Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
##[error]The term **'Trace-VstsEnteringInvocation' is not recognized** as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
  ##[error]The term **'Trace-VstsLeavingInvocation' is not recognized** as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
  ##[error]The term **'Get-VstsInput' is not recognized** as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Please look at the issue again.
I'm happy the task exists, but these errors don't let it work properly.

**Comment by jessehouwing** [comment]
What's your agent version? 1.9x 1.10x? Or 2.x?

**Comment by loshurik** [comment]
@jessehouwing 
Thanks for a quick responce, I'm impressed=)
The agent version is 1.95.3

**Comment by jessehouwing** [comment]
I'm afraid the function being called requires a newer agent and may need
tfs 2015u3... Waiting for @peter to confirm. 1.10x or better 2.x

**Comment by loshurik** [comment]
TFS 14.102.25423.0 is 2015u3 in fact
https://blogs.msdn.microsoft.com/tfssetup/2013/11/21/what-version-of-team-foundation-server-do-i-have/
and agent is 1.95.3 goes for this one
2.x agent version will mean server update as well
please check if possible whether the task is compatible with TFS 2015 update 3

**Comment by jessehouwing** [comment]
I'll leave that to Peter who owns the task. It may take a bit longer. I
highly recommend to upgrade to TFS 2017 for multiple reasons other than the
agent version though. Especially if you're using Azure, because the build
tasks for 2015 are no longer being updated for new versions of the Azure
sdk etc.
