### ISSUE TITLE
TFS Marketplace

### ISSUE THREAD

**Issue by brandonwittwer** [XpiritBV/Vsts-Build-Task-InlinePowershell#7]
Could you push your newest version of your tool to the marketplace?  We recently encountered that "." in the username issue and need that update.

Thanks.  

And nice work.

**Comment by pgroene** [comment]
this should be fixed in the current version. Can you verify that you are running 1.1.6?

**Comment by brandonwittwer** [comment]
Your feedback prompted us to uninstall and reinstall.  Through the process of our TFS upgrades, auto update of extensions wasnt working.  Thanks for your extension!
